plugins {
    id 'application'
}

dependencies {
    implementation project(':Renderer')

    implementation 'com.github.taucher2003:t2003-logger-impl:1.0.2'
	implementation 'com.github.taucher2003:t2003-logger-binder:1.0.2'
}

application {
    mainClass = 'net.buildabrowser.babbrowser.browser.Main'
    applicationDefaultJvmArgs = [
        '-Xms32m',
        '-XX:MaxHeapFreeRatio=10', '-XX:MinHeapFreeRatio=10',
        '-XX:+UnlockExperimentalVMOptions', '-XX:+UseCompactObjectHeaders',
        '-Djava.net.preferIPv4Stack=true'
    ]
}

run {
    // enableAssertions = true
}