plugins {
    id 'application'
}

dependencies {
    implementation project(':Renderer')
}

application {
    mainClass = 'net.buildabrowser.babbrowser.browser.Main'
    applicationDefaultJvmArgs = [
        '-XX:MaxHeapFreeRatio=10', '-XX:MinHeapFreeRatio=10',
        '-XX:+UnlockExperimentalVMOptions', '-XX:+UseCompactObjectHeaders',
        '-Djava.net.preferIPv4Stack=true'
    ]
}

run {
    // enableAssertions = true
}