import org.gradle.nativeplatform.internal.DefaultTargetMachineFactory

subprojects {
	apply plugin: 'java'
	
	repositories {
		mavenCentral()
	}

	dependencies {
		implementation "org.slf4j:slf4j-api:1.7.36"

    testImplementation platform("org.junit:junit-bom:5.10.0")
    testImplementation "org.junit.jupiter:junit-jupiter"
		testRuntimeOnly "org.junit.platform:junit-platform-launcher"
	}

	tasks.withType(Test).configureEach {
		useJUnitPlatform()
		// failOnNoDiscoveredTests = false
	}

	java {
    sourceCompatibility = JavaVersion.VERSION_24
    targetCompatibility = JavaVersion.VERSION_24
	}

}