package net.buildabrowser.babbrowser.htmlparser.tokenize.imp;

import net.buildabrowser.babbrowser.htmlparser.tokenize.TokenizeState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AfterAttributeNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AfterAttributeValueQuotedState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AfterDoctypeNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AfterDoctypePublicIdentifierState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AfterDoctypePublicKeywordState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AfterDoctypeSystemIdentifierState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AfterDoctypeSystemKeywordState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AmbiguousAmpersandState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AttributeNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AttributeValueDoubleQuotedState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AttributeValueSingleQuotedState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.AttributeValueUnquotedState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.BeforeAttributeNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.BeforeAttributeValueState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.BeforeDoctypeNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.BeforeDoctypePublicIdentifierState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.BeforeDoctypeSystemIdentifierState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.BetweenDoctypePublicAndSystemIdentifiersState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.BogusDoctypeState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.CharacterReferenceState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.CommentEndBangState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.CommentEndDashState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.CommentEndState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.CommentLessThanSignBangDashDashState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.CommentLessThanSignBangDashState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.CommentLessThanSignBangState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.CommentStartDashState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.CommentStartState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.CommentState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.DataState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.DecimalCharacterReferenceStartState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.DecimalCharacterReferenceState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.DoctypeNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.DoctypePublicIdentifierDoubleQuotedState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.DoctypePublicIdentifierSingleQuotedState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.DoctypeState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.DoctypeSystemIdentifierDoubleQuotedState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.DoctypeSystemIdentifierSingleQuotedState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.EndTagOpenState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.HexadecimalCharacterReferenceStartState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.HexadecimalCharacterReferenceState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.MarkupDeclarationOpenState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.NamedCharacterReferenceState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.NumericCharacterReferenceEndState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.NumericCharacterReferenceState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.RCDataEndTagNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.RCDataEndTagOpenState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.RCDataLessThanSignState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.RCDataState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.RawTextEndTagNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.RawTextEndTagOpenState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.RawTextLessThanSignState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.RawTextState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataDoubleEscapeEndState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataDoubleEscapeStartState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataDoubleEscapedDashDashState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataDoubleEscapedDashState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataDoubleEscapedLessThanSignState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataDoubleEscapedState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataEndTagNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataEngTagOpenState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataEscapeStartDashState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataEscapeStartState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataEscapedDashDashState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataEscapedDashState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataEscapedEndTagNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataEscapedEndTagOpenState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataEscapedLessThanSignState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataEscapedState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataLessThanSignState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.ScriptDataState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.SelfClosingStartTagState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.TagNameState;
import net.buildabrowser.babbrowser.htmlparser.tokenize.states.TagOpenState;

public final class TokenizeStates {
  
  private TokenizeStates() {}

  public static final TokenizeState AFTER_ATTRIBUTE_NAME_STATE = new AfterAttributeNameState();
  public static final TokenizeState AFTER_ATTRIBUTE_VALUE_QUOTED_STATE = new AfterAttributeValueQuotedState();
  public static final TokenizeState AFTER_DOCTYPE_NAME_STATE = new AfterDoctypeNameState();
  public static final TokenizeState AFTER_DOCTYPE_PUBLIC_IDENTIFIER_STATE = new AfterDoctypePublicIdentifierState();
  public static final TokenizeState AFTER_DOCTYPE_PUBLIC_KEYWORD_STATE = new AfterDoctypePublicKeywordState();
  public static final TokenizeState AFTER_DOCTYPE_SYSTEM_IDENTIFIER_STATE = new AfterDoctypeSystemIdentifierState();
  public static final TokenizeState AFTER_DOCTYPE_SYSTEM_KEYWORD_STATE = new AfterDoctypeSystemKeywordState();
  public static final TokenizeState ATTRIBUTE_NAME_STATE = new AttributeNameState();
  public static final TokenizeState AMBIGUOUS_AMPERSAND_STATE = new AmbiguousAmpersandState();
  public static final TokenizeState ATTRIBUTE_VALUE_DOUBLE_QUOTED_STATE = new AttributeValueDoubleQuotedState();
  public static final TokenizeState ATTRIBUTE_VALUE_SINGLE_QUOTED_STATE = new AttributeValueSingleQuotedState();
  public static final TokenizeState ATTRIBUTE_VALUE_UNQUOTED_STATE = new AttributeValueUnquotedState();
  public static final TokenizeState BEFORE_ATTRIBUTE_NAME_STATE = new BeforeAttributeNameState();
  public static final TokenizeState BEFORE_ATTRIBUTE_VALUE_STATE = new BeforeAttributeValueState();
  public static final TokenizeState BEFORE_DOCTYPE_NAME_STATE = new BeforeDoctypeNameState();
  public static final TokenizeState BEFORE_DOCTYPE_PUBLIC_IDENTIFIER_STATE = new BeforeDoctypePublicIdentifierState();
  public static final TokenizeState BEFORE_DOCTYPE_SYSTEM_IDENTIFIER_STATE = new BeforeDoctypeSystemIdentifierState();
  public static final TokenizeState BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS_STATE = new BetweenDoctypePublicAndSystemIdentifiersState();
  public static final TokenizeState BOGUS_DOCTYPE_STATE = new BogusDoctypeState();
  public static final TokenizeState CHARACTER_REFERENCE_STATE = new CharacterReferenceState();
  public static final TokenizeState COMMENT_END_BANG_STATE = new CommentEndBangState();
  public static final TokenizeState COMMENT_END_DASH_STATE = new CommentEndDashState();
  public static final TokenizeState COMMENT_END_STATE = new CommentEndState();
  public static final TokenizeState COMMENT_LESS_THAN_SIGN_BANG_DASH_DASH_STATE = new CommentLessThanSignBangDashDashState();
  public static final TokenizeState COMMENT_LESS_THAN_SIGN_BANG_DASH_STATE = new CommentLessThanSignBangDashState();
  public static final TokenizeState COMMENT_LESS_THAN_SIGN_BANG_STATE = new CommentLessThanSignBangState();
  public static final TokenizeState COMMENT_LESS_THAN_SIGN_STATE = new CommentLessThanSignBangState();
  public static final TokenizeState COMMENT_START_DASH_STATE = new CommentStartDashState();
  public static final TokenizeState COMMENT_START_STATE = new CommentStartState();
  public static final TokenizeState COMMENT_STATE = new CommentState();
  public static final TokenizeState DATA_STATE = new DataState();
  public static final TokenizeState DECIMAL_CHARACTER_REFERENCE_START_STATE = new DecimalCharacterReferenceStartState();
  public static final TokenizeState DECIMAL_CHARACTER_REFERENCE_STATE = new DecimalCharacterReferenceState();
  public static final TokenizeState DOCTYPE_NAME_STATE = new DoctypeNameState();
  public static final TokenizeState DOCTYPE_PUBLIC_IDENTIFIER_DOUBLE_QUOTED_STATE = new DoctypePublicIdentifierDoubleQuotedState();
  public static final TokenizeState DOCTYPE_PUBLIC_IDENTIFIER_SINGLE_QUOTED_STATE = new DoctypePublicIdentifierSingleQuotedState();
  public static final TokenizeState DOCTYPE_STATE = new DoctypeState();
  public static final TokenizeState DOCTYPE_SYSTEM_IDENTIFIER_DOUBLE_QUOTED_STATE = new DoctypeSystemIdentifierDoubleQuotedState();
  public static final TokenizeState DOCTYPE_SYSTEM_IDENTIFIER_SINGLE_QUOTED_STATE = new DoctypeSystemIdentifierSingleQuotedState();
  public static final TokenizeState END_TAG_OPEN_STATE = new EndTagOpenState();
  public static final TokenizeState HEXADECIMAL_CHARACTER_REFERENCE_START_STATE = new HexadecimalCharacterReferenceStartState();
  public static final TokenizeState HEXADECIMAL_CHARACTER_REFERENCE_STATE = new HexadecimalCharacterReferenceState();
  public static final TokenizeState MARKUP_DECLARATION_OPEN_STATE = new MarkupDeclarationOpenState();
  public static final TokenizeState NAMED_CHARACTER_REFERENCE_STATE = new NamedCharacterReferenceState();
  public static final TokenizeState NUMERIC_CHARACTER_REFERENCE_END_STATE = new NumericCharacterReferenceEndState();
  public static final TokenizeState NUMERIC_CHARACTER_REFERENCE_STATE = new NumericCharacterReferenceState();
  public static final TokenizeState RAW_TEXT_END_TAG_NAME_STATE = new RawTextEndTagNameState();
  public static final TokenizeState RAW_TEXT_END_TAG_OPEN_STATE = new RawTextEndTagOpenState();
  public static final TokenizeState RAW_TEXT_LESS_THAN_SIGN_STATE = new RawTextLessThanSignState();
  public static final TokenizeState RAW_TEXT_STATE = new RawTextState();
  public static final TokenizeState RCDATA_END_TAG_NAME_STATE = new RCDataEndTagNameState();
  public static final TokenizeState RCDATA_END_TAG_OPEN_STATE = new RCDataEndTagOpenState();
  public static final TokenizeState RCDATA_LESS_THAN_SIGN_STATE = new RCDataLessThanSignState();
  public static final TokenizeState RCDATA_STATE = new RCDataState();
  public static final TokenizeState SCRIPT_DATA_DOUBLE_ESCAPED_DASH_DASH_STATE = new ScriptDataDoubleEscapedDashDashState();
  public static final TokenizeState SCRIPT_DATA_DOUBLE_ESCAPED_DASH_STATE = new ScriptDataDoubleEscapedDashState();
  public static final TokenizeState SCRIPT_DATA_DOUBLE_ESCAPED_LESS_THAN_SIGN_STATE = new ScriptDataDoubleEscapedLessThanSignState();
  public static final TokenizeState SCRIPT_DATA_DOUBLE_ESCAPED_STATE = new ScriptDataDoubleEscapedState();
  public static final TokenizeState SCRIPT_DATA_DOUBLE_ESCAPE_END_STATE = new ScriptDataDoubleEscapeEndState();
  public static final TokenizeState SCRIPT_DATA_DOUBLE_ESCAPE_START_STATE = new ScriptDataDoubleEscapeStartState();
  public static final TokenizeState SCRIPT_DATA_END_TAG_NAME_STATE = new ScriptDataEndTagNameState();
  public static final TokenizeState SCRIPT_DATA_END_TAG_OPEN_STATE = new ScriptDataEngTagOpenState();
  public static final TokenizeState SCRIPT_DATA_ESCAPED_DASH_DASH_STATE = new ScriptDataEscapedDashDashState();
  public static final TokenizeState SCRIPT_DATA_ESCAPED_DASH_STATE = new ScriptDataEscapedDashState();
  public static final TokenizeState SCRIPT_DATA_ESCAPED_END_TAG_NAME_STATE = new ScriptDataEscapedEndTagNameState();
  public static final TokenizeState SCRIPT_DATA_ESCAPED_END_TAG_OPEN_STATE = new ScriptDataEscapedEndTagOpenState();
  public static final TokenizeState SCRIPT_DATA_ESCAPED_LESS_THAN_SIGN_STATE = new ScriptDataEscapedLessThanSignState();
  public static final TokenizeState SCRIPT_DATA_ESCAPED_STATE = new ScriptDataEscapedState();
  public static final TokenizeState SCRIPT_DATA_ESCAPE_START_DASH_STATE = new ScriptDataEscapeStartDashState();
  public static final TokenizeState SCRIPT_DATA_ESCAPE_START_STATE = new ScriptDataEscapeStartState();
  public static final TokenizeState SCRIPT_DATA_LESS_THAN_SIGN_STATE = new ScriptDataLessThanSignState();
  public static final TokenizeState SCRIPT_DATA_STATE = new ScriptDataState();
  public static final TokenizeState SELF_CLOSING_START_TAG_STATE = new SelfClosingStartTagState();
  public static final TokenizeState TAG_NAME_STATE = new TagNameState();
  public static final TokenizeState TAG_OPEN_STATE = new TagOpenState();

}
