package net.buildabrowser.babbrowser.a11y.core.aom;

public enum AriaRole {

  ALERT, ALERTDIALOGUE, APPLICATION, ARTICLE, BANNER, BLOCKQUOTE,
  BUTTON, CAPTION, CELL, CHECKBOX, CODE, COLUMNHEADER, COMBOBOX,
  COMMENT, COMPLEMENTARY, CONTENTINFO,  DEFINITION, DELETION, DIALOG,
  DIRECTORY, DOCUMENT, EMPHASIS, FEED, FIGURE, FORM, GENERIC, GRID,
  GRIDCELL, GROUP, HEADING, IMAGE, IMG, INSERTION, LINK, LIST, LISTBOX,
  LISTITEM, LOG, MAIN, MARK, MARQUEE, MATH, MENU, MENUBAR, MENUITEM,
  MENUITEMCHECKBOX, MENUITEMRADIO, METER, NAVIGATION, NONE, NOTE, OPTION,
  PARAGRAPH, PRESENTATION, PROGRESSBAR, RADIO, RADIOGROUP, REGION, ROW,
  ROWGROUP, ROWHEADER, SCROLLBAR, SEARCH, SEARCHBOX, SECTIONFOOTER,
  SECTIONHEADER, SEPARATOR, SLIDER, SPINBUTTON, STATUS, STRONG,
  SUBSCRIPT, SUGGESTION, SUPERSCRIPT, SWITCH, TAB, TABLE, TABLIST,
  TABPANEL, TERM, TEXTBOX, TIME, TIMER, TOOLBAR, TOOLTIP, TREE, TREEGRID,
  TREEITEM,
  
  // Non-Standard Extensions
  STATICTEXT;

}
