package net.buildabrowser.babbrowser.a11y.core.aom;

public enum AriaEvent {
  ACTIVEDESCENDANT, BUSY, CHECKED, CURRENT, DISABLED, DESCRIBEDBY,
  DROPEFFECT, EXPANDED, GRABBED, HIDDEN, INVALID, LABEL, LABELLEDBY,
  PRESSED, READONLY, REQUIRED, SELECTED, VALUENOW, VALUETEXT
}
