plugins {
    id 'java-library'
}

dependencies {
    api project(':PainterCore')
    api project(':Network')
    api project(':Fetch')
    api project(':CSSBase')
    api project(':HTML')
    api project(':DebuggerCore')
    implementation project(':Common')
    implementation project(':HTMLParser')
    implementation project(':CSSEngine')

    implementation("com.google.code.gson:gson:2.13.2")
}