package net.buildabrowser.babbrowser.a11y.core;

public enum AriaProperty {

  ACTIVEDESCENDANT, ATOMIC, AUTOCOMPLETE, BRAILLELABEL,
  BRAILLEROLEDESCRIPTION, BUSY, CHECKED, COLCOUNT, COLINDEX, COLINDEXTEXT,
  COLSPAN, CONTROLS, CURRENT, DESCRIBEDBY, DESCRIPTION, DETAILS, DISABLED,
  DROPEFFECT, ERRORMESSAGE, EXPANDED, FLOWTO, GRABBED, HASPOPUP, HIDDEN,
  INVALID, KEYSHORTCUTS, LABEL, LABELLEDBY, LEVEL, LIVE, MODAL, MULTILINE,
  MULTISELECTABLE, ORIENTATION, OWNS, PLACEHOLDER, POSINSET, PRESSED,
  READONLY, RELEVANT, REQUIRED, ROLEDESCRIPTION, ROWCOUNT, ROWINDEX,
  ROWINDEXTEXT, ROWSPAN, SELECTED, SETSIZE, SORT, VALUEMAX, VALUEMIN,
  VALUENOW, VALUETEXT


}
